micronaut:
  application:
    name: javaServerless
datasources:
  default:
    url: jdbc:mysql://lambdatest.c4qoxufww9zr.us-west-2.rds.amazonaws.com/booksdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: pfrank
    password: NotAPassword
