micronaut:
  application:
    name: javaServerless
datasources:
  default:
    url: jdbc:h2:mem:devDb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: iWantThisToFail #This should not be used in the test
    password: ''
    dialect: H2