micronaut:
  application:
    name: javaServerless
datasources:
  default:
    url: jdbc:h2:mem:devDb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: FAIL
    password: ''
    dialect: H2
flyway:
  datasources:
    default:
      locations: classpath:migrations