micronaut:
  application:
    name: javaServerless
datasources:
  default:
    url: jdbc:h2:mem:devDb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: FAIL #On purpose to detect failure cause this shouldn't be used
    password: ''
    dialect: H2
